### PR TITLE
chore(deps): upgrade phpstan to ^0.12

### PR DESCRIPTION
**Pull request by mazsudo**

### CODE REVIEW

**Comment by mazsudo** [comment]
let's discuss if we add type on iterables..else it can can turn off by setting checkMissingIterableValueType: false in phpstan.neon.dist

**Comment by mazsudo** [comment]
waiting for https://github.com/ekino/phpstan-sonata/pull/12 to be merged

**Comment by mremi** [comment]
Please rebase

**Comment by mazsudo** [comment]
done @mremi

**Pull request merged**
